// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3aYGub-5ya230V0nh-Hldfj68uvsMtac',
    appId: '1:235905596651:web:b0e173671a970fc53392ae',
    messagingSenderId: '235905596651',
    projectId: 'fir-project-6dd9d',
    authDomain: 'fir-project-6dd9d.firebaseapp.com',
    storageBucket: 'fir-project-6dd9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXkrPuBHSZGa-cADXA56QigLDhukieyU',
    appId: '1:235905596651:android:d92ea3ca9abd0bbc3392ae',
    messagingSenderId: '235905596651',
    projectId: 'fir-project-6dd9d',
    storageBucket: 'fir-project-6dd9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNl-dPewLMB7h_alK015O7JLa_7wHqFo',
    appId: '1:235905596651:ios:25b1649148948a863392ae',
    messagingSenderId: '235905596651',
    projectId: 'fir-project-6dd9d',
    storageBucket: 'fir-project-6dd9d.appspot.com',
    iosBundleId: 'com.tech.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNl-dPewLMB7h_alK015O7JLa_7wHqFo',
    appId: '1:235905596651:ios:25b1649148948a863392ae',
    messagingSenderId: '235905596651',
    projectId: 'fir-project-6dd9d',
    storageBucket: 'fir-project-6dd9d.appspot.com',
    iosBundleId: 'com.tech.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3aYGub-5ya230V0nh-Hldfj68uvsMtac',
    appId: '1:235905596651:web:42337ede118397fd3392ae',
    messagingSenderId: '235905596651',
    projectId: 'fir-project-6dd9d',
    authDomain: 'fir-project-6dd9d.firebaseapp.com',
    storageBucket: 'fir-project-6dd9d.appspot.com',
  );
}
